#!/bin/bash

tmp=$(mktemp -d)
function rm_tmp {
    [ -d "$tmp" ] && rm -rd "$tmp"
}
trap rm_tmp EXIT
trap 'trap - EXIT; rm_tmpfile; exit -1' INT PIPE TERM

cd $tmp

echo '
\documentclass{article}
\usepackage{amsmath,amssymb,amsfonts}
\pagestyle{empty}
\begin{document}
    $$
        $1
    $$
\end{document}' > main.tex

lualatex main.tex > /dev/null
pdfcrop main.pdf crop.pdf > /dev/null
pdftoppm -png crop.pdf -scale-to-x -1 -scale-to-y 200 > main.png

convert -negate main.png neg.png
img2sixel neg.png

cd - > /dev/null
